# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import shorten.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kwrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, validators=[shorten.validators.validator_url, shorten.validators.validate_dot_com])),
                ('shortcode', models.CharField(blank=True, max_length=15, unique=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
