# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import shorten.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwrg',
            name='url',
            field=models.CharField(max_length=250, validators=[shorten.validators.validator_url]),
        ),
    ]
