# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20180719_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwrg',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
