# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import shorten.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20180719_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwrg',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kwrg',
            name='url',
            field=models.CharField(max_length=250, validators=[shorten.validators.validator_url, shorten.validators.validate_dot_com]),
        ),
    ]
