# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import shorten.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0004_auto_20180719_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwrg',
            name='url',
            field=models.CharField(max_length=250, validators=[shorten.validators.validator_url, shorten.validators.validate_dot_com, shorten.validators.validaotr_http]),
        ),
    ]
